version: 0.0
os: linux

files:
  - source: target/myapp.war
    destination: /var/www/myapp

hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 300

  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 300

  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300

  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 300
