version: 0.2

phases:
  install:
    commands:
      - echo "Skipping Node installation"
  build:
    commands:
      - echo "Static Web Project - No build step needed"
  post_build:
    commands:
      - echo "Build Complete"

artifacts:
  files:
    - '**/*'
